# Generated by Django 2.2 on 2021-06-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companystock',
            old_name='company_stocks',
            new_name='company_stocks_as_comma_seperated_numbers',
        ),
    ]
